### ISSUE TITLE
Fix travis CI

### ISSUE THREAD

**Issue by t-b** [tango-controls/TangoSourceDistribution#72]
Does currently fail, see https://travis-ci.org/github/tango-controls/TangoSourceDistribution.

The reason is

```
     [exec] sphinx-build -b singlehtml -d build/doctrees   source build/singlehtml

     [exec] Running Sphinx v1.8.5

     [exec] loading translations [en]... done

     [exec] Registering meta-labels...

     [exec] registering lang 

     [exec] registering audience 

     [exec] ... meta-labels registered.

     [exec] making output directory...

     [exec] Makefile:63: recipe for target 'singlehtml' failed

     [exec] 

     [exec] Theme error:

     [exec] sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)

     [exec] make: *** [singlehtml] Error 2
```

Fix that by:
- [ ] Installing sphinx_rtd_theme
- [ ] Install pip packages with a fixed version so that we are not suprised again by new versions and breaking changes

**Comment by mliszcz** [comment]
One comment - I think that the problem is due to pulling master code into 9.3.4 branch of tango-doc here: https://github.com/tango-controls/tango-doc/commit/8b47a555ec6d3eb0701554d5c80f97befb17af27. And tango-doc master since January requires sphinx_rtd_theme: https://github.com/tango-controls/tango-doc/commit/c409572d866de55bfc8d959d991ac2ee0f47f468

When I added documentation tree to the source distribution, I wanted to avoid adding to ant build any steps that could modify your operating system or your environment, thus I installed package dependencies from CI job definition:
https://github.com/tango-controls/TangoSourceDistribution/blob/75863a6edde3e82c2e1cd5ad97d7a8cb43739638/.travis.yml#L15

Tango-doc provides `requirements.txt`, maybe we can use it somehow.
