### ISSUE TITLE
"tango start" doesn't work for new MariaDB versions

### ISSUE THREAD

**Issue by dmiego** [tango-controls/TangoSourceDistribution#84]
I've noticed that on MariaDB 10.4+ there is no proccess called "mysqld". So simple "tango start" command doesn't work as it supposed to.

![image](https://user-images.githubusercontent.com/13482645/89267501-fdf1fe00-d63f-11ea-825b-c3a7b05f63ef.png)
![image](https://user-images.githubusercontent.com/13482645/89266813-101f6c80-d63f-11ea-9515-e2c26ee9929c.png)

**Comment by mliszcz** [comment]
Maybe we could remove the check for `mysqld` process presence, because it does not do anything useful except printing a message. And a message will be printed anyway by DataBaseds when it cannot connect to database (reason = CANNOT_CONNECT_MYSQL).

Checking for specific process name is not reliable as it can easily be broken by creating a symlink to mysqld/mariadbd.

**Comment by t-b** [comment]
I'll handle that.
